name: Hassfest

on:
  push:
  pull_request:

jobs:
  hassfest:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v4"
      - name: "Hassfest"
        uses: home-assistant/actions/hassfest@master
